// Expansion Scripts - Automated filesystem expansion for VMs

use serde::{Deserialize, Serialize};

/// Filesystem type
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum FilesystemType {
    Ext4,
    Xfs,
    Btrfs,
    LVM,      // LVM with ext4
    LVMXfs,   // LVM with xfs
}

impl FilesystemType {
    pub fn from_string(s: &str) -> Self {
        match s.to_lowercase().as_str() {
            "ext4" => FilesystemType::Ext4,
            "xfs" => FilesystemType::Xfs,
            "btrfs" => FilesystemType::Btrfs,
            "lvm" | "lvm-ext4" => FilesystemType::LVM,
            "lvm-xfs" => FilesystemType::LVMXfs,
            _ => FilesystemType::Ext4, // Default
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            FilesystemType::Ext4 => "ext4",
            FilesystemType::Xfs => "xfs",
            FilesystemType::Btrfs => "btrfs",
            FilesystemType::LVM => "lvm-ext4",
            FilesystemType::LVMXfs => "lvm-xfs",
        }
    }
}

/// Expansion script configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpansionScript {
    pub filesystem_type: FilesystemType,
    pub device: String,
    pub lvm_vg: Option<String>,
    pub lvm_lv: Option<String>,
    pub partition_number: Option<u32>,
    pub dry_run: bool,
}

impl ExpansionScript {
    pub fn new(filesystem_type: FilesystemType, device: impl Into<String>) -> Self {
        Self {
            filesystem_type,
            device: device.into(),
            lvm_vg: None,
            lvm_lv: None,
            partition_number: None,
            dry_run: false,
        }
    }

    pub fn with_lvm(mut self, vg: impl Into<String>, lv: impl Into<String>) -> Self {
        self.lvm_vg = Some(vg.into());
        self.lvm_lv = Some(lv.into());
        self
    }

    pub fn with_partition(mut self, num: u32) -> Self {
        self.partition_number = Some(num);
        self
    }

    pub fn dry_run(mut self, enabled: bool) -> Self {
        self.dry_run = enabled;
        self
    }
}

/// Script generator for filesystem expansion
pub struct ScriptGenerator;

impl ScriptGenerator {
    /// Generate complete expansion script
    pub fn generate(config: &ExpansionScript) -> String {
        let mut script = String::new();

        script.push_str("#!/bin/bash\n");
        script.push_str("# Automated Filesystem Expansion Script\n");
        script.push_str("# Generated by Zorvia\n");
        script.push_str("\n");
        script.push_str("set -e  # Exit on error\n");
        script.push_str("\n");

        if config.dry_run {
            script.push_str("echo '=== DRY RUN MODE - No changes will be made ==='\n");
            script.push_str("DRY_RUN=true\n\n");
        }

        script.push_str(&Self::generate_checks());
        script.push_str("\n");

        script.push_str(&Self::generate_rescan(&config.device));
        script.push_str("\n");

        match config.filesystem_type {
            FilesystemType::LVM | FilesystemType::LVMXfs => {
                script.push_str(&Self::generate_lvm_expansion(config));
            }
            FilesystemType::Ext4 | FilesystemType::Xfs | FilesystemType::Btrfs => {
                script.push_str(&Self::generate_partition_expansion(config));
            }
        }

        script.push_str("\n");
        script.push_str(&Self::generate_verification());

        script
    }

    /// Generate initial checks
    fn generate_checks() -> String {
        r#"echo "=== Pre-Flight Checks ==="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Display current disk usage
echo "Current disk usage:"
df -h
echo ""
lsblk
echo ""
"#.to_string()
    }

    /// Generate disk rescan
    fn generate_rescan(device: &str) -> String {
        let device_name = device.trim_start_matches("/dev/");

        format!(r#"echo "=== Rescanning disk: {} ==="
if [ -z "$DRY_RUN" ]; then
    echo 1 | tee /sys/class/block/{}/device/rescan
    sleep 2
    echo "Disk rescanned"
else
    echo "[DRY RUN] Would rescan {}"
fi
"#, device, device_name, device)
    }

    /// Generate LVM expansion commands
    fn generate_lvm_expansion(config: &ExpansionScript) -> String {
        let vg = config.lvm_vg.as_deref().unwrap_or("vg");
        let lv = config.lvm_lv.as_deref().unwrap_or("root");
        let device = &config.device;
        let partition = if let Some(num) = config.partition_number {
            format!("{}{}", device, num)
        } else {
            format!("{}3", device) // Default to partition 3
        };

        let resize_cmd = match config.filesystem_type {
            FilesystemType::LVMXfs => "xfs_growfs /",
            _ => &format!("resize2fs /dev/mapper/{}-{}", vg, lv),
        };

        format!(r#"echo "=== LVM Expansion ==="

# Extend partition if needed
if [ -z "$DRY_RUN" ]; then
    echo "Extending partition..."
    growpart {} $(echo {} | grep -o '[0-9]*$') || echo "Partition already at maximum size"
else
    echo "[DRY RUN] Would run: growpart {} $(echo {} | grep -o '[0-9]*$')"
fi

# Resize physical volume
echo "Resizing physical volume..."
if [ -z "$DRY_RUN" ]; then
    pvresize {}
    pvdisplay {}
else
    echo "[DRY RUN] Would run: pvresize {}"
fi

# Check volume group
echo "Volume group status:"
if [ -z "$DRY_RUN" ]; then
    vgdisplay {}
else
    echo "[DRY RUN] Would display vg: {}"
fi

# Extend logical volume
echo "Extending logical volume..."
if [ -z "$DRY_RUN" ]; then
    lvextend -l +100%FREE /dev/mapper/{}-{}
    lvdisplay /dev/mapper/{}-{}
else
    echo "[DRY RUN] Would run: lvextend -l +100%FREE /dev/mapper/{}-{}"
fi

# Resize filesystem
echo "Resizing filesystem..."
if [ -z "$DRY_RUN" ]; then
    {}
else
    echo "[DRY RUN] Would run: {}"
fi
"#, device, partition, device, partition, partition, partition, partition,
   vg, vg, vg, lv, vg, lv, vg, lv, resize_cmd, resize_cmd)
    }

    /// Generate partition expansion commands
    fn generate_partition_expansion(config: &ExpansionScript) -> String {
        let device = &config.device;
        let partition_num = config.partition_number.unwrap_or(1);
        let partition = format!("{}{}", device, partition_num);

        let resize_cmd = match config.filesystem_type {
            FilesystemType::Xfs => "xfs_growfs /",
            FilesystemType::Btrfs => "btrfs filesystem resize max /",
            _ => &format!("resize2fs {}", partition),
        };

        format!(r#"echo "=== Partition Expansion ==="

# Extend partition
echo "Extending partition {}..."
if [ -z "$DRY_RUN" ]; then
    growpart {} {}
else
    echo "[DRY RUN] Would run: growpart {} {}"
fi

# Resize filesystem
echo "Resizing {} filesystem..."
if [ -z "$DRY_RUN" ]; then
    {}
else
    echo "[DRY RUN] Would run: {}"
fi
"#, partition, device, partition_num, device, partition_num,
   config.filesystem_type.as_str(), resize_cmd, resize_cmd)
    }

    /// Generate verification commands
    fn generate_verification() -> String {
        r#"echo ""
echo "=== Verification ==="
echo "New disk usage:"
df -h
echo ""
lsblk
echo ""
echo "=== Expansion Complete ==="
"#.to_string()
    }

    /// Generate one-liner script for quick execution
    pub fn generate_oneliner(filesystem_type: &FilesystemType, device: &str) -> String {
        match filesystem_type {
            FilesystemType::LVM => {
                format!(
                    "echo 1 | sudo tee /sys/class/block/{}/device/rescan && \
                     sudo pvresize {}3 && \
                     sudo lvextend -l +100%FREE /dev/mapper/vg-root && \
                     sudo resize2fs /dev/mapper/vg-root",
                    device.trim_start_matches("/dev/"),
                    device
                )
            }
            FilesystemType::LVMXfs => {
                format!(
                    "echo 1 | sudo tee /sys/class/block/{}/device/rescan && \
                     sudo pvresize {}3 && \
                     sudo lvextend -l +100%FREE /dev/mapper/vg-root && \
                     sudo xfs_growfs /",
                    device.trim_start_matches("/dev/"),
                    device
                )
            }
            FilesystemType::Ext4 => {
                format!(
                    "echo 1 | sudo tee /sys/class/block/{}/device/rescan && \
                     sudo growpart {} 1 && \
                     sudo resize2fs {}1",
                    device.trim_start_matches("/dev/"),
                    device,
                    device
                )
            }
            FilesystemType::Xfs => {
                format!(
                    "echo 1 | sudo tee /sys/class/block/{}/device/rescan && \
                     sudo growpart {} 1 && \
                     sudo xfs_growfs /",
                    device.trim_start_matches("/dev/"),
                    device
                )
            }
            FilesystemType::Btrfs => {
                format!(
                    "echo 1 | sudo tee /sys/class/block/{}/device/rescan && \
                     sudo growpart {} 1 && \
                     sudo btrfs filesystem resize max /",
                    device.trim_start_matches("/dev/"),
                    device
                )
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_filesystem_type_from_string() {
        assert_eq!(FilesystemType::from_string("ext4"), FilesystemType::Ext4);
        assert_eq!(FilesystemType::from_string("xfs"), FilesystemType::Xfs);
        assert_eq!(FilesystemType::from_string("lvm"), FilesystemType::LVM);
    }

    #[test]
    fn test_script_generation_lvm() {
        let script_config = ExpansionScript::new(FilesystemType::LVM, "/dev/vda")
            .with_lvm("ubuntu-vg", "ubuntu-lv")
            .with_partition(3);

        let script = ScriptGenerator::generate(&script_config);

        assert!(script.contains("#!/bin/bash"));
        assert!(script.contains("pvresize"));
        assert!(script.contains("lvextend"));
        assert!(script.contains("resize2fs"));
    }

    #[test]
    fn test_script_generation_ext4() {
        let script_config = ExpansionScript::new(FilesystemType::Ext4, "/dev/sda")
            .with_partition(1);

        let script = ScriptGenerator::generate(&script_config);

        assert!(script.contains("growpart"));
        assert!(script.contains("resize2fs"));
    }

    #[test]
    fn test_dry_run_script() {
        let script_config = ExpansionScript::new(FilesystemType::LVM, "/dev/vda")
            .dry_run(true);

        let script = ScriptGenerator::generate(&script_config);

        assert!(script.contains("DRY RUN"));
        assert!(script.contains("[DRY RUN]"));
    }

    #[test]
    fn test_oneliner_generation() {
        let oneliner = ScriptGenerator::generate_oneliner(&FilesystemType::LVM, "/dev/vda");

        assert!(oneliner.contains("pvresize"));
        assert!(oneliner.contains("lvextend"));
        assert!(oneliner.contains("resize2fs"));
    }
}
