apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: web-server
    os: fedora
    os.version: '39'
  name: web-server
  namespace: default
spec:
  running: false
  runStrategy: null
  template:
    metadata:
      labels:
        os: fedora
        os.version: '39'
    spec:
      domain:
        resources:
          requests:
            memory: 16Gi
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        memory:
          guest: 16Gi
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
            bootOrder: 1
          - name: datadisk
            disk:
              bus: virtio
            bootOrder: 2
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            model: virtio
            masquerade: {}
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:39
          imagePullPolicy: IfNotPresent
      - name: datadisk
        emptyDisk:
          capacity: 20Gi
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: zorvia
            password: zorvia
            chpasswd: { expire: False }
            ssh_pwauth: True
            package_update: true
            packages:
              - qemu-guest-agent
            runcmd:
              - [ systemctl, enable, qemu-guest-agent ]
              - [ systemctl, start, qemu-guest-agent ]
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 30
