apiVersion: v2
name: zorvia
description: Zorvia — KubeVirt VM management platform (API + console)
type: application
version: 0.3.3
appVersion: "0.3.3"
home: https://zyvor.dev
sources:
  - https://github.com/zyvorai/zorvia
maintainers:
  - name: ZyvorAI Labs
    email: info@zyvor.dev
keywords:
  - kubevirt
  - virtualization
  - kubernetes
