use serde::{Deserialize, Serialize};

/// Shell completion generator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionGenerator {
    pub shell: CompletionShell,
    pub binary_name: String,
}

/// Target shell for completions
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CompletionShell {
    Bash,
    Zsh,
    Fish,
    PowerShell,
    Elvish,
}

impl std::fmt::Display for CompletionShell {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CompletionShell::Bash => write!(f, "bash"),
            CompletionShell::Zsh => write!(f, "zsh"),
            CompletionShell::Fish => write!(f, "fish"),
            CompletionShell::PowerShell => write!(f, "powershell"),
            CompletionShell::Elvish => write!(f, "elvish"),
        }
    }
}

impl CompletionShell {
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "bash" => Some(CompletionShell::Bash),
            "zsh" => Some(CompletionShell::Zsh),
            "fish" => Some(CompletionShell::Fish),
            "powershell" | "pwsh" => Some(CompletionShell::PowerShell),
            "elvish" => Some(CompletionShell::Elvish),
            _ => None,
        }
    }

    pub fn file_extension(&self) -> &str {
        match self {
            CompletionShell::Bash => "bash",
            CompletionShell::Zsh => "zsh",
            CompletionShell::Fish => "fish",
            CompletionShell::PowerShell => "ps1",
            CompletionShell::Elvish => "elv",
        }
    }

    pub fn install_instructions(&self) -> String {
        match self {
            CompletionShell::Bash => "# Add to ~/.bashrc:\n\
                 source <(zorvia completions bash)\n\
                 # Or save to file:\n\
                 zorvia completions bash > /etc/bash_completion.d/zorvia"
                .to_string(),
            CompletionShell::Zsh => "# Add to ~/.zshrc:\n\
                 source <(zorvia completions zsh)\n\
                 # Or save to file:\n\
                 zorvia completions zsh > ~/.zsh/completions/_zorvia"
                .to_string(),
            CompletionShell::Fish => "# Save to fish completions directory:\n\
                 zorvia completions fish > ~/.config/fish/completions/zorvia.fish"
                .to_string(),
            CompletionShell::PowerShell => "# Add to PowerShell profile:\n\
                 zorvia completions powershell | Out-String | Invoke-Expression"
                .to_string(),
            CompletionShell::Elvish => "# Add to ~/.elvish/rc.elv:\n\
                 eval (zorvia completions elvish | slurp)"
                .to_string(),
        }
    }
}

impl CompletionGenerator {
    pub fn new(shell: CompletionShell) -> Self {
        Self {
            shell,
            binary_name: "zorvia".to_string(),
        }
    }

    pub fn with_binary_name(mut self, name: impl Into<String>) -> Self {
        self.binary_name = name.into();
        self
    }

    pub fn generate(&self) -> String {
        match self.shell {
            CompletionShell::Bash => self.generate_bash(),
            CompletionShell::Zsh => self.generate_zsh(),
            CompletionShell::Fish => self.generate_fish(),
            CompletionShell::PowerShell => self.generate_powershell(),
            CompletionShell::Elvish => self.generate_elvish(),
        }
    }

    fn generate_bash(&self) -> String {
        format!(
            r#"# Bash completion for {name}
# Generated by {name} completions bash

_{name}_completions() {{
    local cur prev opts
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    # Main commands
    local commands="create list get delete start stop restart generate templates template validate status clone resources export wizard batch profiles profile blueprints blueprint deploy health recommend snapshot-create snapshot-list snapshot-get snapshot-delete snapshot-restore monitor-live monitor-stats monitor-compare monitor-top disk-expand disk-health disk-script disk-usage network-list network-get network-bandwidth network-traffic network-policies network-policy migrate migration-status migration-list ha-config ha-status evacuate-node evacuation-status backup-create backup-list backup-get backup-delete backup-restore backup-verify backup-schedules backup-schedule-create recovery-plan recovery-execute security-scan security-assess security-harden security-profiles compliance-check compliance-report audit-list audit-get audit-stats cost-analyze cost-summary cost-report budget-list budget-create budget-status cost-optimize cost-waste cost-forecast automation-list automation-create automation-get automation-run workflow-list workflow-create workflow-get workflow-run workflow-executions schedule-list schedule-create logs-query logs-stats logs-patterns metrics-collect metrics-query metrics-snapshot alerts-list alerts-create alerts-active alerts-resolve insights-generate recommendations trends-analyze health-check tenants-list tenants-create tenants-show tenants-delete users-list users-create users-assign-role roles-list roles-show roles-create quotas-list quotas-create quotas-show groups-list groups-create groups-add-user completions config-save config-load config-list config-delete diff init info"

    case "${{prev}}" in
        {name})
            COMPREPLY=( $(compgen -W "${{commands}}" -- "${{cur}}") )
            return 0
            ;;
        --template|-t)
            local templates="ubuntu fedora centos debian rhel windows almalinux rocky opensuse alpine arch oracle freebsd flatcar talos"
            COMPREPLY=( $(compgen -W "${{templates}}" -- "${{cur}}") )
            return 0
            ;;
        --output|-o)
            COMPREPLY=( $(compgen -W "yaml json table" -- "${{cur}}") )
            return 0
            ;;
        --format)
            COMPREPLY=( $(compgen -W "yaml json csv" -- "${{cur}}") )
            return 0
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish powershell elvish" -- "${{cur}}") )
            return 0
            ;;
    esac

    if [[ "${{cur}}" == -* ]] ; then
        local flags="--namespace --kubeconfig --verbose --help --version"
        COMPREPLY=( $(compgen -W "${{flags}}" -- "${{cur}}") )
        return 0
    fi

    COMPREPLY=( $(compgen -W "${{commands}}" -- "${{cur}}") )
}}

complete -F _{name}_completions {name}
"#,
            name = self.binary_name
        )
    }

    fn generate_zsh(&self) -> String {
        format!(
            r#"#compdef {name}

# Zsh completion for {name}
# Generated by {name} completions zsh

_zorvia() {{
    local -a commands
    commands=(
        'create:Create a new VM'
        'list:List VMs in the namespace'
        'get:Get details of a VM'
        'delete:Delete a VM'
        'start:Start a VM'
        'stop:Stop a VM'
        'restart:Restart a VM'
        'generate:Generate a VM manifest'
        'templates:List available templates'
        'template:Show template details'
        'validate:Validate a VM configuration file'
        'status:Show detailed VM status'
        'clone:Clone an existing VM'
        'resources:Show resource usage summary'
        'export:Export VM configuration'
        'wizard:Interactive VM creation wizard'
        'batch:Create multiple VMs from batch config'
        'profiles:List VM resource profiles'
        'profile:Show specific profile details'
        'blueprints:List multi-VM blueprints'
        'blueprint:Show specific blueprint details'
        'deploy:Deploy a multi-VM blueprint'
        'health:Run health check on a VM'
        'recommend:Get resource recommendations'
        'snapshot-create:Create a VM snapshot'
        'snapshot-list:List snapshots'
        'snapshot-get:Show snapshot details'
        'snapshot-delete:Delete a snapshot'
        'snapshot-restore:Restore VM from snapshot'
        'monitor-live:Show live performance monitoring'
        'monitor-stats:Get performance statistics'
        'monitor-compare:Compare performance of multiple VMs'
        'monitor-top:Show top VMs by resource usage'
        'completions:Generate shell completions'
        'config-save:Save VM configuration as template'
        'config-load:Load a saved configuration'
        'config-list:List saved configurations'
        'config-delete:Delete a saved configuration'
        'diff:Compare two VM configurations'
        'init:Initialize a new zorvia project'
        'info:Show environment and version information'
    )

    _arguments \
        '--namespace[Kubernetes namespace]:namespace:' \
        '--kubeconfig[Path to kubeconfig file]:kubeconfig:_files' \
        '(-v --verbose){{-v,--verbose}}[Enable verbose logging]' \
        '1:command:->command' \
        '*::arg:->args'

    case $state in
        command)
            _describe -t commands 'zorvia command' commands
            ;;
    esac
}}

_zorvia "$@"
"#,
            name = self.binary_name
        )
    }

    fn generate_fish(&self) -> String {
        format!(
            r#"# Fish completion for {name}
# Generated by {name} completions fish

# Disable file completions for the main command
complete -c {name} -f

# Global flags
complete -c {name} -l namespace -d 'Kubernetes namespace'
complete -c {name} -l kubeconfig -d 'Path to kubeconfig file' -r -F
complete -c {name} -s v -l verbose -d 'Enable verbose logging'

# Main commands
complete -c {name} -n __fish_use_subcommand -a create -d 'Create a new VM'
complete -c {name} -n __fish_use_subcommand -a list -d 'List VMs in the namespace'
complete -c {name} -n __fish_use_subcommand -a get -d 'Get details of a VM'
complete -c {name} -n __fish_use_subcommand -a delete -d 'Delete a VM'
complete -c {name} -n __fish_use_subcommand -a start -d 'Start a VM'
complete -c {name} -n __fish_use_subcommand -a stop -d 'Stop a VM'
complete -c {name} -n __fish_use_subcommand -a restart -d 'Restart a VM'
complete -c {name} -n __fish_use_subcommand -a generate -d 'Generate a VM manifest'
complete -c {name} -n __fish_use_subcommand -a templates -d 'List available templates'
complete -c {name} -n __fish_use_subcommand -a template -d 'Show template details'
complete -c {name} -n __fish_use_subcommand -a validate -d 'Validate a VM config file'
complete -c {name} -n __fish_use_subcommand -a status -d 'Show detailed VM status'
complete -c {name} -n __fish_use_subcommand -a clone -d 'Clone an existing VM'
complete -c {name} -n __fish_use_subcommand -a resources -d 'Show resource usage summary'
complete -c {name} -n __fish_use_subcommand -a export -d 'Export VM configuration'
complete -c {name} -n __fish_use_subcommand -a wizard -d 'Interactive VM creation wizard'
complete -c {name} -n __fish_use_subcommand -a batch -d 'Create VMs from batch config'
complete -c {name} -n __fish_use_subcommand -a profiles -d 'List VM resource profiles'
complete -c {name} -n __fish_use_subcommand -a blueprints -d 'List multi-VM blueprints'
complete -c {name} -n __fish_use_subcommand -a deploy -d 'Deploy a multi-VM blueprint'
complete -c {name} -n __fish_use_subcommand -a health -d 'Run health check'
complete -c {name} -n __fish_use_subcommand -a recommend -d 'Get resource recommendations'
complete -c {name} -n __fish_use_subcommand -a completions -d 'Generate shell completions'
complete -c {name} -n __fish_use_subcommand -a config-save -d 'Save configuration'
complete -c {name} -n __fish_use_subcommand -a config-load -d 'Load configuration'
complete -c {name} -n __fish_use_subcommand -a config-list -d 'List saved configurations'
complete -c {name} -n __fish_use_subcommand -a config-delete -d 'Delete saved configuration'
complete -c {name} -n __fish_use_subcommand -a diff -d 'Compare two VM configurations'
complete -c {name} -n __fish_use_subcommand -a init -d 'Initialize zorvia project'
complete -c {name} -n __fish_use_subcommand -a info -d 'Show environment info'

# Template completions
complete -c {name} -n '__fish_seen_subcommand_from create generate' -s t -l template -d 'Use a template' -a 'ubuntu fedora centos debian rhel windows almalinux rocky opensuse alpine arch oracle freebsd flatcar talos'

# Output format completions
complete -c {name} -n '__fish_seen_subcommand_from list get export' -s o -l output -d 'Output format' -a 'yaml json table'

# Completions shell argument
complete -c {name} -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish powershell elvish'
"#,
            name = self.binary_name
        )
    }

    fn generate_powershell(&self) -> String {
        format!(
            r#"# PowerShell completion for {name}
# Generated by {name} completions powershell

Register-ArgumentCompleter -Native -CommandName '{name}' -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @(
        'create', 'list', 'get', 'delete', 'start', 'stop', 'restart',
        'generate', 'templates', 'template', 'validate', 'status', 'clone',
        'resources', 'export', 'wizard', 'batch', 'profiles', 'profile',
        'blueprints', 'blueprint', 'deploy', 'health', 'recommend',
        'snapshot-create', 'snapshot-list', 'snapshot-get', 'snapshot-delete',
        'snapshot-restore', 'monitor-live', 'monitor-stats', 'monitor-compare',
        'monitor-top', 'completions', 'config-save', 'config-load',
        'config-list', 'config-delete', 'diff', 'init', 'info'
    )

    $commands | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
    }}
}}
"#,
            name = self.binary_name
        )
    }

    fn generate_elvish(&self) -> String {
        format!(
            r#"# Elvish completion for {name}
# Generated by {name} completions elvish

edit:completion:arg-completer[{name}] = {{|@words|
    var commands = [
        create list get delete start stop restart generate templates template
        validate status clone resources export wizard batch profiles profile
        blueprints blueprint deploy health recommend snapshot-create snapshot-list
        snapshot-get snapshot-delete snapshot-restore monitor-live monitor-stats
        monitor-compare monitor-top completions config-save config-load
        config-list config-delete diff init info
    ]

    if (eq (count $words) 2) {{
        each {{|cmd| put $cmd}} $commands
    }}
}}
"#,
            name = self.binary_name
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_completion_shell_from_str() {
        assert_eq!(CompletionShell::parse("bash"), Some(CompletionShell::Bash));
        assert_eq!(CompletionShell::parse("zsh"), Some(CompletionShell::Zsh));
        assert_eq!(CompletionShell::parse("fish"), Some(CompletionShell::Fish));
        assert_eq!(
            CompletionShell::parse("powershell"),
            Some(CompletionShell::PowerShell)
        );
        assert_eq!(
            CompletionShell::parse("pwsh"),
            Some(CompletionShell::PowerShell)
        );
        assert_eq!(
            CompletionShell::parse("elvish"),
            Some(CompletionShell::Elvish)
        );
        assert_eq!(CompletionShell::parse("unknown"), None);
    }

    #[test]
    fn test_completion_shell_display() {
        assert_eq!(CompletionShell::Bash.to_string(), "bash");
        assert_eq!(CompletionShell::Zsh.to_string(), "zsh");
        assert_eq!(CompletionShell::Fish.to_string(), "fish");
        assert_eq!(CompletionShell::PowerShell.to_string(), "powershell");
        assert_eq!(CompletionShell::Elvish.to_string(), "elvish");
    }

    #[test]
    fn test_completion_shell_file_extension() {
        assert_eq!(CompletionShell::Bash.file_extension(), "bash");
        assert_eq!(CompletionShell::Zsh.file_extension(), "zsh");
        assert_eq!(CompletionShell::Fish.file_extension(), "fish");
        assert_eq!(CompletionShell::PowerShell.file_extension(), "ps1");
        assert_eq!(CompletionShell::Elvish.file_extension(), "elv");
    }

    #[test]
    fn test_completion_generator_new() {
        let gen = CompletionGenerator::new(CompletionShell::Bash);
        assert_eq!(gen.shell, CompletionShell::Bash);
        assert_eq!(gen.binary_name, "zorvia");
    }

    #[test]
    fn test_completion_generator_with_binary_name() {
        let gen = CompletionGenerator::new(CompletionShell::Zsh).with_binary_name("vc");
        assert_eq!(gen.binary_name, "vc");
    }

    #[test]
    fn test_generate_bash_completions() {
        let gen = CompletionGenerator::new(CompletionShell::Bash);
        let output = gen.generate();
        assert!(output.contains("_zorvia_completions"));
        assert!(output.contains("complete -F"));
        assert!(output.contains("create"));
        assert!(output.contains("list"));
    }

    #[test]
    fn test_generate_zsh_completions() {
        let gen = CompletionGenerator::new(CompletionShell::Zsh);
        let output = gen.generate();
        assert!(output.contains("#compdef"));
        assert!(output.contains("_zorvia"));
        assert!(output.contains("create:Create a new VM"));
    }

    #[test]
    fn test_generate_fish_completions() {
        let gen = CompletionGenerator::new(CompletionShell::Fish);
        let output = gen.generate();
        assert!(output.contains("complete -c zorvia"));
        assert!(output.contains("__fish_use_subcommand"));
    }

    #[test]
    fn test_generate_powershell_completions() {
        let gen = CompletionGenerator::new(CompletionShell::PowerShell);
        let output = gen.generate();
        assert!(output.contains("Register-ArgumentCompleter"));
    }

    #[test]
    fn test_generate_elvish_completions() {
        let gen = CompletionGenerator::new(CompletionShell::Elvish);
        let output = gen.generate();
        assert!(output.contains("edit:completion:arg-completer"));
    }

    #[test]
    fn test_install_instructions() {
        let bash = CompletionShell::Bash.install_instructions();
        assert!(bash.contains("bashrc"));

        let zsh = CompletionShell::Zsh.install_instructions();
        assert!(zsh.contains("zshrc"));

        let fish = CompletionShell::Fish.install_instructions();
        assert!(fish.contains("fish"));

        let ps = CompletionShell::PowerShell.install_instructions();
        assert!(ps.contains("PowerShell"));

        let elv = CompletionShell::Elvish.install_instructions();
        assert!(elv.contains("elvish"));
    }
}
