import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated from the docs/ folder structure. Add _category_.json files
// under docs/ later to customize labels/ordering per category.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
