name: CI Markdown Links

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/ci-markdown.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
      - ".github/workflows/ci-markdown.yml"
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "no"
          folder-path: "docs/,."
          file-extension: ".md"
          max-depth: 2
        continue-on-error: true
