name: CI Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "15 6 * * 4"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep OSS
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Scan
        run: |
          semgrep scan --config=auto --error --quiet \
            --exclude=target --exclude=node_modules --exclude=website/build \
            || true
