name: CI YAML Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/ci-yaml.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/ci-yaml.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Install yamllint
        run: pip install --user "yamllint==1.37.1"
      - name: Lint
        run: |
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 160}, truthy: disable, comments: disable, document-start: disable}}" \
            .github/workflows charts deploy \
            || true
